/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styled from "styled-components";

const data = [
  {
    title: "Quick Links",
    links: [
      { text: "Home", url: "/" },
      { text: "Library", url: "/library" },
      { text: "Terms & Conditions", url: "/terms" },
      { text: "Privacy Policy", url: "/privacy" },
    ],
  },
  {
    title: "Company Details",
    details: [
      "Company number:",
      "Address:",
      "Email:",
    ],
  },
];

function MyComponent() {
  return (
    <PageWrapper>
      <Header>
        <HeaderContent>
          <Nav>
            <NavItem active>
              <NavLink>Home</NavLink>
              <ActiveIndicator />
            </NavItem>
            <NavLink>Pricing</NavLink>
            <NavLink>Library</NavLink>
          </Nav>
          <Logo src="https://cdn.builder.io/api/v1/image/assets/TEMP/d1f13f7661e7851847b3359023b4da75654f5f0a6103f9d821e966676cbe9fed?apiKey=2f8ba804799c4e819d1f2564600c89db&" alt="Logo" />
          <AuthButtons>
            <LoginButton>Login</LoginButton>
            <SignupButton>Sign in</SignupButton>
          </AuthButtons>
        </HeaderContent>
      </Header>
      <Main>
        <SignInTitle>Sign in</SignInTitle>
        <SignInForm>
          <InputLabel htmlFor="email">Email*</InputLabel>
          <InputField id="email" type="email" />
          <InputLabel htmlFor="password">Password*</InputLabel>
          <InputField id="password" type="password" />
          <FormActions>
            <RememberMe>
              <Checkbox />
              <CheckboxLabel>Remember me</CheckboxLabel>
            </RememberMe>
            <ForgotPassword>Lost your password</ForgotPassword>
            <SubmitButton>Submit</SubmitButton>
          </FormActions>
        </SignInForm>
      </Main>
      <Footer>
        <FooterBackground src="https://cdn.builder.io/api/v1/image/assets/TEMP/7dd24f32ba3caf76bcffea14b8ae9135c1b4041a6e4ffcc744f35e0648233c72?apiKey=2f8ba804799c4e819d1f2564600c89db&" alt="Footer Background" />
        <FooterContent>
          <FooterTop>
            <FooterColumn>
              <FooterLogo src="https://cdn.builder.io/api/v1/image/assets/TEMP/189991cce57f87bcc18fffbc20e9b4b4a32ae089fc85f5c45770f5371c4526ee?apiKey=2f8ba804799c4e819d1f2564600c89db&" alt="Footer Logo" />
            </FooterColumn>
            {data.map((item, index) => (
              <FooterColumn key={index}>
                <FooterSection>
                  <FooterTitle>{item.title}</FooterTitle>
                  {item.links && item.links.map((link, linkIndex) => (
                    <FooterLink key={linkIndex} href={link.url}>{link.text}</FooterLink>
                  ))}
                  {item.details && item.details.map((detail, detailIndex) => (
                    <FooterDetail key={detailIndex}>{detail}</FooterDetail>
                  ))}
                </FooterSection>
              </FooterColumn>
            ))}
            <FooterColumn>
              <SocialIcons src="https://cdn.builder.io/api/v1/image/assets/TEMP/6ed75a414ef350b36b327f760b315442d69e01cbf4930e8bbcf2e4f11cbc6ddb?apiKey=2f8ba804799c4e819d1f2564600c89db&" alt="Social Icons" />
            </FooterColumn>
          </FooterTop>
          <FooterDivider />
          <Copyright>© 2023 Readaway. All Right Reserved.</Copyright>
        </FooterContent>
      </Footer>
    </PageWrapper>
  );
}

const PageWrapper = styled.div`
  background-color: #000;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const Header = styled.header`
  display: flex;
  width: 100%;
  padding: 27px 20px 0;
  justify-content: center;

  @media (max-width: 991px) {
    padding-top: 20px;
  }
`;

const HeaderContent = styled.div`
  display: flex;
  max-width: 1278px;
  width: 100%;
  align-items: center;
  gap: 20px;
  color: #fff;
  justify-content: space-between;

  @media (max-width: 991px) {
    flex-wrap: wrap;
  }
`;

const Nav = styled.nav`
  display: flex;
  gap: 20px;
  font-size: 16px;
  font-weight: 700;
  white-space: nowrap;
  justify-content: space-between;
  margin: auto 0;

  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const NavItem = styled.div`
  display: flex;
  flex-direction: column;
  ${props => props.active && `
    & > ${NavLink} {
      color: #e0583c;
    }
  `}

  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const NavLink = styled.a`
  font-family: Open Sans, sans-serif;
  text-decoration: none;
  color: inherit;
`;

const ActiveIndicator = styled.div`
  background-color: #e0583c;
  margin-top: 8px;
  height: 4px;
`;

const Logo = styled.img`
  aspect-ratio: 3.13;
  object-fit: contain;
  width: 162px;
  max-width: 100%;
`;

const AuthButtons = styled.div`
  display: flex;
  gap: 18px;
  font-size: 15px;
  font-weight: 600;
  margin: auto 0;
`;

const LoginButton = styled.button`
  font-family: Open Sans, sans-serif;
  border-radius: 7px;
  background-color: #e0583c;
  white-space: nowrap;
  justify-content: center;
  padding: 13px 35px;
  border: none;
  color: #fff;
  cursor: pointer;

  @media (max-width: 991px) {
    white-space: initial;
    padding: 13px 20px;
  }
`;

const SignupButton = styled(LoginButton)`
  align-items: start;
`;

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 0 20px;
`;

const SignInTitle = styled.h1`
  color: #fff;
  margin-top: 63px;
  font: 600 16px Open Sans, sans-serif;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const SignInForm = styled.form`
  border-radius: 10px;
  border: 1px solid rgba(255, 255, 255, 1);
  background-color: #000;
  display: flex;
  margin-top: 59px;
  width: 958px;
  max-width: 100%;
  flex-direction: column;
  color: #fff;
  font-weight: 600;
  padding: 52px 40px;

  @media (max-width: 991px) {
    margin-top: 40px;
    padding: 40px 20px;
  }
`;

const InputLabel = styled.label`
  font: 16px Open Sans, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const InputField = styled.input`
  border-radius: 5px;
  border: 1px solid rgba(52, 52, 52, 1);
  background-color: #fff;
  margin-top: 18px;
  height: 61px;
  padding: 0 20px;
  font: 16px Open Sans, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const FormActions = styled.div`
  display: flex;
  margin-top: 17px;
  gap: 20px;
  justify-content: space-between;
  padding: 0 2px;

  @media (max-width: 991px) {
    flex-wrap: wrap;
  }
`;

const RememberMe = styled.div`
  display: flex;
  gap: 12px;
  align-items: center;
`;

const Checkbox = styled.div`
  border-radius: 3px;
  border: 1px solid rgba(52, 52, 52, 1);
  background-color: #222;
  width: 20px;
  height: 20px;
`;

const CheckboxLabel = styled.label`
  font-family: Open Sans, sans-serif;
  flex-grow: 1;
  flex-basis: auto;
  margin: auto 0;
`;

const ForgotPassword = styled.a`
  font-family: Open Sans, sans-serif;
  align-self: end;
  margin-top: 9px;
  color: inherit;
  text-decoration: none;
`;

const SubmitButton = styled.button`
  border: 1px solid rgba(224, 88, 60, 1);
  border-radius: 7px;
  background-color: #e0583c;
  white-space: nowrap;
  justify-content: center;
  padding: 25px 48px;
  font: 22px Open Sans, sans-serif;
  color: #fff;
  cursor: pointer;

  @media (max-width: 991px) {
    white-space: initial;
    padding: 25px 20px;
  }
`;

const Footer = styled.footer`
  display: flex;
  flex-direction: column;
  overflow: hidden;
  align-self: stretch;
  position: relative;
  min-height: 413px;
  margin-top: 97px;
  width: 100%;
  align-items: center;
  padding: 80px 60px 24px;

  @media (max-width: 991px) {
    margin-top: 40px;
    padding: 40px 20px;
  }
`;

const FooterBackground = styled.img`
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

const FooterContent = styled.div`
  position: relative;
  display: flex;
  width: 100%;
  max-width: 1128px;
  flex-direction: column;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const FooterTop = styled.div`
  display: flex;
  gap: 20px;

  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
    gap: 0px;
    padding-right: 20px;
  }
`;

const FooterColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 25%;
  margin-left: ${props => props.index === 0 ? '0px' : '20px'};

  @media (max-width: 991px) {
    width: 100%;
    margin-left: 0;
    margin-top: 40px;
  }
`;

const FooterLogo = styled.img`
  aspect-ratio: 3.23;
  object-fit: contain;
  width: 150px;
  margin-top: 4px;
  max-width: 100%;

  @media (max-width: 991px) {
    margin-top: 0;
  }
`;

const FooterSection = styled.div`
  display: flex;
  flex-grow: 1;
  flex-direction: column;
  font-size: 16px;
  color: #fff;
  font-weight: 400;
`;

const FooterTitle = styled.h3`
  font: 700 25px Open Sans, sans-serif;
  margin: 0;
`;

const FooterLink = styled.a`
  font-family: Open Sans, sans-serif;
  margin-top: 30px;
  color: inherit;
  text-decoration: none;

  &:first-of-type {
    margin-top: 37px;
  }
`;

const FooterDetail = styled.p`
  font-family: Open Sans, sans-serif;
  margin-top: 25px;

  &:first-of-type {
    margin-top: 32px;
  }
`;

const SocialIcons = styled.img`
  aspect-ratio: 7.14;
  object-fit: contain;
  width: 199px;
  max-width: 100%;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const FooterDivider = styled.hr`
  border: none;
  border-top: 1px solid rgba(85, 85, 85, 1);
  background-color: #555;
  margin-top: 68px;
  height: 1px;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const Copyright = styled.p`
  color: #fff;
  align-self: end;
  margin: 24px 70px 0 0;
  font: 400 13px Open Sans, sans-serif;

  @media (max-width: 991px) {
    margin-right: 10px;
  }
`;

export default MyComponent;